### ISSUE TITLE
equalp error

### ISSUE THREAD

**Issue by angelacastaneda** [mattyonweb/denote-graph#1]
I am using denote and wanted to try out your denote-graph package. I installed your program with straight, but running `M-x denote-graph-generate-dot-file` from anywhere returns:

```
cl--position: Symbol’s function definition is void: equalp
```

here's my denote config in case there's anything wrong here:

```elisp
(use-package denote
    :ensure t
    :custom
    (denote-directory (expand-file-name "~/Documents/org/denote"))
    (denote-save-buffers nil)
    (denote-infer-keywords t)
    (denote-sort-keywords t)
    (denote-prompts '(title keywords)))
```

**Comment by mattyonweb** [comment]
Hi @angelacastaneda ,

this may be a problem with the `cl` or `cl-lib` libraries, but I can't replicate it at the moment. If you don't mind, I would like to ask you:

- What version of emacs are you using (M-x emacs-version)? 

- What do you get if you run the following with M-x eval-expression: `(cl-equalp 0 1)`?

In the meanwhile, you could try and modify [line 108](https://github.com/mattyonweb/denote-graph/blob/master/denote-graph.el#L108) from:

`for tuple in (cl-delete-duplicates (denote-graph--flatten graph) :test 'equalp)`

to:

`for tuple in (cl-delete-duplicates (denote-graph--flatten graph) :test 'cl-equalp)`

And see if that makes it work.

Let me know :)

**Comment by angelacastaneda** [comment]
1. `GNU Emacs 29.4 (build 2, x86_64-alpine-linux-musl, GTK+ Version 3.24.42, cairo version 1.18.0) of 2024-06-22`.
2. C-x C-e'ing `(cl-equalp 0 1)` returns nil. doing the same with equalp gave me an error.
3. changing that line was all that I needed; DOT file fully generated.

Thanks so much for the help!

**Comment by mattyonweb** [comment]
Thanks for the feedback! 

I've updated the code accordingly with commit 74e6e547394ef6e0c667cc6144913c28c88f1521, so as to not rely anymore on the obsolete `equalp` for comparisons.
